# Build concrete-ntt
name: Cargo Build

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cargo-builds:
    runs-on: ["self-hosted", "m1mac"]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          override: true

      - name: Run pcc checks
        run: |
          make pcc

      - name: Build release
        run: |
          make build

      - name: Build release no-std
        run: |
          make build_no_std

      - name: Build benchmarks
        run: |
          make build_bench

      - name: Test debug
        run: make test

      - name: Test no-std
        run: make test_no_std

      - name: Test nightly
        run: make test_nightly

      - name: Test no-std nightly
        run: make test_no_std_nightly
